# Generated by Django 3.1.2 on 2022-04-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
