# Generated by Django 3.1.2 on 2022-03-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketType', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ticketPrice', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='discountRate',
            field=models.FloatField(default=0.0),
        ),
    ]
