# Generated by Django 4.0.2 on 2022-03-13 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_alter_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged'),
            preserve_default=False,
        ),
    ]
