# Generated by Django 4.0.2 on 2022-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0003_film_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(max_length=1),
        ),
    ]
