# Generated by Django 4.0.2 on 2022-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_remove_film_image_remove_film_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.URLField(default='https://m.media-amazon.com/images/M/MV5BYTExZTdhY2ItNGQ1YS00NjJlLWIxMjYtZTI1MzNlMzY0OTk4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg'),
            preserve_default=False,
        ),
    ]
