# Generated by Django 3.1.2 on 2022-03-31 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEFlix', '0004_auto_20220331_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.showing'),
        ),
        migrations.AlterField(
            model_name='club',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubaccount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.club'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.film'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.screens'),
        ),
    ]
