# Generated by Django 4.0.2 on 2022-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_film_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='film',
            name='short_description',
            field=models.CharField(default='short desc', max_length=300),
            preserve_default=False,
        ),
    ]
