# Generated by Django 4.0.2 on 2022-04-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_notification_link_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='link_data',
            new_name='href_data',
        ),
    ]
