# Generated by Django 4.0.2 on 2022-04-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_rename_link_notification_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
