# Generated by Django 4.0.2 on 2022-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_alter_booking_id_alter_clubaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
