# Generated by Django 3.1.2 on 2022-03-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEFlix', '0007_auto_20220324_0553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
        migrations.DeleteModel(
            name='CinemaManager',
        ),
        migrations.RemoveField(
            model_name='club',
            name='account',
        ),
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='club',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='landline',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RepresentativeAccount',
        ),
    ]
