# Generated by Django 4.0.2 on 2022-04-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0007_alter_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='href',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='href_data',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
