# Generated by Django 3.1.2 on 2022-03-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0007_auto_20220324_0553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
        migrations.DeleteModel(
            name='CinemaManager',
        ),
        migrations.RemoveField(
            model_name='club',
            name='representative',
        ),
        migrations.DeleteModel(
            name='RepresentativeAccount',
        ),
    ]
