# Generated by Django 3.1.2 on 2022-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0009_club_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
