# Generated by Django 3.1.2 on 2022-03-25 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEFlix', '0010_auto_20220325_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
