# Generated by Django 3.1.2 on 2022-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0012_auto_20220409_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubaccount',
            name='expiry_date',
            field=models.CharField(max_length=300),
        ),
    ]
