# Generated by Django 3.1.2 on 2022-03-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0013_auto_20220325_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.clubaccount'),
        ),
    ]
