# Generated by Django 4.0.3 on 2022-05-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0014_booking_time_booked_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='email',
            field=models.CharField(default='default@gmail.com', max_length=24),
        ),
        migrations.AlterField(
            model_name='clubrepresentative',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
