# Generated by Django 3.1.2 on 2022-03-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0015_auto_20220325_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.clubaccount'),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='landline',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
