# Generated by Django 4.0.2 on 2022-05-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0016_remove_club_email_alter_clubrepresentative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
