# Generated by Django 3.1.2 on 2022-03-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0016_auto_20220325_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='account',
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='club',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.club'),
            preserve_default=False,
        ),
    ]
